services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./ci/docker/php/Dockerfile
    volumes:
      - storage:/var/www/storage
      - public:/var/www/public
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_VERSION: ${APP_VERSION:-0.1.0}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: database
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "9000:9000"
    networks:
      - laravel_app
    depends_on:
      - database

  webserver:
    image: nginx:1-alpine
    restart: unless-stopped
    depends_on:
      - app
      - database
    ports:
      - "${APP_PORT:-9020}:80"
    #      - "443:80"
    volumes:
      - ./ci/docker/webserver/nginx-prod.conf:/etc/nginx/templates/default.conf.template
      - ./volumes/nginx/logs:/var/log/nginx/
      - public:/var/www/public
      - storage:/var/www/storage
    networks:
      - laravel_app

  database:
    # LTS (log-tem support) | Jammy (Ubuntu 22.04)
    image: mariadb:lts-jammy
    restart: unless-stopped
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - laravel_app

  redis:
    image: bitnami/redis:7.4
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    volumes:
      - ./.volumes/redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - laravel_app

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    ports:
      - "${PMA_PORT:-9030}:80"
    environment:
      PMA_HOST: database
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - database
    networks:
      - laravel_app

volumes:
  v-database:
  storage:
  public:

networks:
  laravel_app:
    driver: bridge
